#: import main main

OdenzymeRoot:

<OdenzymeRoot>:
	MapMenuForm:

<MapMenuForm>:
	orientation: "vertical"

	Button: 
		size_hint_y: 33
		text: "Draw new map - not working"
		on_press: app.root.to_new_map()
	Button: 
		size_hint_y: 33
		text: "Browse map -not working"
	Button:
		size_hint_y: 33
		text: "Upload map -not working"

<NewMap>:
	Button:
		width: 400
		size_hint_x: None
		text: " A margin for \n writting some text, \n place some buttons \n or whatever"

	BoxLayout:
		Map:

<Map>	
	RelativeLayout:
		Label: 
			text: "Title of your work"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/2,(root.height/12)*11
			#on_press: root.new_enzyme()
	#DRAWING TOOLS -TOP LEFT BUTTONS-
		Button: 
			text: "Enzyme"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*9
			on_press: root.new_enzyme()

		Button: 
			text: "Compound"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*8
		Button: 
			text: "Gene"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*7

		Button: 
			text: "Erase"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*6

		Button: 
			text: "Zoom"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*5

		Button: 
			text: "Search"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: root.width/20,(root.height/12)*4

	#MENU TOOLS -BOTTOM RIGHT BUTTONS-

		Button: 
			text: "Help"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: (root.width/1.2),(root.height/12)*4

		Button: 
			text: "Simulate"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: (root.width/1.2),(root.height/12)*3
		Button: 
			text: "Back"
			width: root.width/10
			size_hint_x: None
			height: root.height/14
			size_hint_y: None
			pos: (root.width/1.2),(root.height/12)*2




